version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: php-apache-full
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    restart: unless-stopped
